service: backoffice-test-backend

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-1
  memorySize: 128
  profile: serverless_admin

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: false
    pythonRequirements:
      dockerizePip: non-linux

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
